<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Status Name</name>
   <tag></tag>
   <elementGuidId>869565e1-13ff-4912-affb-12f23347b3f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'status_name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#status_name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Status Name&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e62c819d-bb85-4a8a-82a1-aa34807a98da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full h-12 px-4 rounded-2xl border border-border bg-white</value>
      <webElementGuid>11fc1a2f-fd53-42ae-9008-75338dbca3d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>status_name</value>
      <webElementGuid>28d40236-c709-4302-aba4-6796dc3270ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>status_name</value>
      <webElementGuid>05822eb0-f56a-4f3f-91f2-ead7e5bfbed1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-03c9923ab33b3ffcd3ff2c11e1a222fc</value>
      <webElementGuid>4266f41b-adcf-4be5-81cc-b15f4a0ec1c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'status_name']</value>
      <webElementGuid>daa244b8-0ea9-4261-b129-b2c31fa83a35</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'status_name']</value>
      <webElementGuid>e78fca42-dce6-4546-8460-bb403e51c35b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'status_name' and @name = 'status_name']</value>
      <webElementGuid>fc872770-8cdb-4fe8-a37c-5fcb41be30be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
