<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Ilustration</name>
   <tag></tag>
   <elementGuidId>c9512bfc-4895-4bbd-a71c-cd5adf3dce1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.cursor-pointer:nth-child(2) [name=&quot;categories\[\]&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' cursor-pointer ') and (name() = 'label') and (position() = 2)]//*[@name = 'categories[]']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Ilustration&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cb29eb65-0e86-4494-b3eb-4aa57729e534</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>98c290a6-c552-4582-8993-c7dd96c691be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>categories[]</value>
      <webElementGuid>8f4fffff-965c-43d0-9757-510e72553bbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>236e4712-3297-475f-acd7-22f4ee7d0abb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mr-2</value>
      <webElementGuid>6d2e1d4d-2fb0-4835-be9d-0ab7d2153a0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-a651c1b931f6ecfa932b9b79aaab6170</value>
      <webElementGuid>9cb37f60-639a-458a-a5d7-1524d91ac8a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' cursor-pointer ') and (name() = 'label') and (position() = 2)]//*[@name = 'categories[]']</value>
      <webElementGuid>1f9954f4-024d-4818-b866-fbb7ff2e8fa6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' cursor-pointer ') and (name() = 'label') and (position() = 2)]//*[@name = 'categories[]']</value>
      <webElementGuid>d7f1adc8-9f21-42ea-a667-3f5f3be77304</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'categories[]']</value>
      <webElementGuid>aba6a807-0ae2-4415-b306-5c5cf4c4888e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
