<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Deadline</name>
   <tag></tag>
   <elementGuidId>1191b92b-303d-4e51-899a-03131cdb4533</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#deadline</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'deadline']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Deadline&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c48fc960-9ee5-48f6-ae62-b5651208b5af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>1b4a320b-1281-4bda-9b7c-58d5f57756a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>deadline</value>
      <webElementGuid>af688f72-5dd7-4906-a813-ccbdf01ca4c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>deadline</value>
      <webElementGuid>d171b132-1194-4f97-971e-4c8191796450</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full h-12 px-4 rounded-2xl border border-border</value>
      <webElementGuid>42332489-e681-4cb2-9adb-3300589e63ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-b65d863ea592569b16d0e210222900c1</value>
      <webElementGuid>57a484a1-5a10-4d8a-94de-04ca16cb7afd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'deadline']</value>
      <webElementGuid>d503245a-aee3-40f5-97a2-72daa232058a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'deadline']</value>
      <webElementGuid>9c34b24d-7a8a-4ae4-9fef-f15c5bb59d67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'deadline' and @name = 'deadline']</value>
      <webElementGuid>e5aae19b-bc8a-4853-bf9f-53f3830497cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
