<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Project Name</name>
   <tag></tag>
   <elementGuidId>4e633c0a-f6cb-4cac-944a-aa0a401157c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nama_proyek</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'nama_proyek']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Project Name&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>66fc1b2a-b506-4b47-b901-7b61067e44a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full h-12 px-4 rounded-2xl border border-border bg-white</value>
      <webElementGuid>419968a1-ea09-45ca-b2b2-81235236c915</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nama_proyek</value>
      <webElementGuid>ae40e884-24ad-4d97-a4f8-5872a975fe18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nama_proyek</value>
      <webElementGuid>cab29d4f-faca-4a30-94e9-75125138bcb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-bfcd2d4337f92fe42788086afa328fdb</value>
      <webElementGuid>c09194b0-290e-446a-8034-89d7dc03afbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'nama_proyek']</value>
      <webElementGuid>67fd364f-c450-44da-93f1-ab69c54e0e9f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'nama_proyek']</value>
      <webElementGuid>53c633a3-22ec-4b9e-ac0f-3387c1dce512</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'nama_proyek' and @name = 'nama_proyek']</value>
      <webElementGuid>4e20943e-7af7-4aba-99f6-d3ef671c977b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
