<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Framer</name>
   <tag></tag>
   <elementGuidId>a75d0075-d14d-47c8-a563-613110681d29</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.cursor-pointer:nth-child(4) [name=&quot;categories\[\]&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' cursor-pointer ') and (name() = 'label') and (position() = 4)]//*[@name = 'categories[]']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Framer&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>881a2bad-c22c-417d-90ce-78f40132f2e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>3b55e63a-ed1d-457d-bf34-a732b774c4de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>categories[]</value>
      <webElementGuid>37d4b956-deca-4551-a2a6-9afd22b2abf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>6b926f4e-fb82-4f32-b756-a251a6af757f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mr-2</value>
      <webElementGuid>0eb5d3ff-ee5e-4f9f-83d3-6c827af2e4c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-b2022d4cf8ff92cc9e09537286e3e2bd</value>
      <webElementGuid>be2d0478-ab9c-4a0d-b16e-e9c48c105a07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' cursor-pointer ') and (name() = 'label') and (position() = 4)]//*[@name = 'categories[]']</value>
      <webElementGuid>98cba7df-2479-4cce-85ff-349e543dbaef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' cursor-pointer ') and (name() = 'label') and (position() = 4)]//*[@name = 'categories[]']</value>
      <webElementGuid>6beead58-3218-4024-8f82-415206982349</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'categories[]']</value>
      <webElementGuid>c7cf0d66-23c8-45e1-9907-a7697e9fd23b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
