<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_WebApp</name>
   <tag></tag>
   <elementGuidId>74ba3958-067c-4cf9-8d6a-ae3b625e1405</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.cursor-pointer:nth-child(7) [name=&quot;categories\[\]&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' cursor-pointer ') and (name() = 'label') and (position() = 7)]//*[@name = 'categories[]']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;WebApp&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3b37d7f5-fcea-4f3d-aa4d-4936b6ee81c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>111b742c-4c0e-4ce8-ab06-c171a5fc5758</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>categories[]</value>
      <webElementGuid>c3c6cb01-5999-443c-849f-27b8d2def343</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>1a9d35aa-a8d3-46c8-a2fb-33b628c76885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mr-2</value>
      <webElementGuid>370bce1d-5c31-4cf7-ae11-38f4a731244d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-e51c3bc60688b27cf3ba02faaec3ecc6</value>
      <webElementGuid>6815c00b-6b78-42b6-881e-c89c562fd563</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' cursor-pointer ') and (name() = 'label') and (position() = 7)]//*[@name = 'categories[]']</value>
      <webElementGuid>30757162-d64c-4efe-b996-0e6be2c45fdf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' cursor-pointer ') and (name() = 'label') and (position() = 7)]//*[@name = 'categories[]']</value>
      <webElementGuid>4e25e786-4e7e-4c77-9a9c-898ab1ccb0fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'categories[]']</value>
      <webElementGuid>7e3ab582-4b16-424d-a016-908596c1ec34</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
