<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_nama_klien</name>
   <tag></tag>
   <elementGuidId>870986fe-4b0f-4727-aae8-f09e626618c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nama_klien</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'nama_klien']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#nama_klien</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6374c1a9-b276-41c0-b537-56f151396d97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1d7d7107-26b0-4d8d-bc1a-aaf15931b2da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nama_klien</value>
      <webElementGuid>46ae77d4-6d99-4239-bf07-013efc51bb81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nama_klien</value>
      <webElementGuid>b5c28a17-e5d0-4410-ba35-a75922781f2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full h-12 px-4 rounded-2xl border border-border</value>
      <webElementGuid>867e811a-6253-4d40-a4b8-d77e08138658</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-15f6092c08a4b444020a731828181687</value>
      <webElementGuid>8202d491-fa13-4de8-b979-980160895e33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'nama_klien']</value>
      <webElementGuid>f67def0f-14fd-48aa-8bf8-644f738e5cc0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'nama_klien']</value>
      <webElementGuid>207c691f-865c-48e2-bb57-02b41a7b2e2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'nama_klien' and @name = 'nama_klien']</value>
      <webElementGuid>34cf4e22-9683-4dc4-ac03-92a8781f4802</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
