blank_issues_enabled: false
contact_links:
  - name: Question / Discussion
    url: https://github.com/jayyidjidan/ProjectManagement/discussions
    about: Use Discussions for questions that aren't a bug report
